### PR TITLE
Cancel 4k characters messages

### PR DESCRIPTION
**Pull request by Rushaway**
Some people can trigger 4k characters with bhop hyperscrool stats. Impressive.
Cancel the message in this case..

### CODE REVIEW

**Comment by maximee-leroyy** [comment]
why cancel ?
just split no ?

**Comment by Rushaway** [comment]
Can't split more stats ?

**Comment by maximee-leroyy** [comment]
wdym

**Comment by Rushaway** [comment]
The stats part is too long for create a message pt3. It will need to split this https://github.com/srcdslab/sm-plugin-AntiBhopCheat/blob/4b904f2104fce1398a059fa702d2823b1ba5f49f/addons/sourcemod/scripting/AntiBhopCheat.sp#L700

**Comment by maximee-leroyy** [comment]
Mhhh i think we can just update the discord plugin to make it split messages if its a really big one (add a parameter to Discord_SendMessage like `autosplit`)

**Comment by Rushaway** [comment]
yeah i already think about it. But it can make a bad split..
In this exemple if the truncat happen in stats message and not at the end of lines it will be fully broken to understand it.

**Comment by maximee-leroyy** [comment]
Ah yes i see !

**Comment by maximee-leroyy** [comment]
So can you try to split this msg ?

**Comment by maximee-leroyy** [comment]
i was thinking, maybe we can try to add a function to the discord plugin to attach a file with the message in it if its too long!

**Comment by Rushaway** [comment]
Yeah, it can do the job this way.

**Comment by Rushaway** [comment]
Archived due to this issue https://github.com/srcdslab/sm-plugin-Discord/issues/4

**Pull request closed without merging**
